import { execFileSync } from "node:child_process";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import Database from "better-sqlite3";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
let tempDir: string; let dbPath: string; let applicationsDir: string;
function run() { return JSON.parse(execFileSync(process.execPath, ["scripts/backfill-application-artifacts.mjs", "--db", dbPath, "--applications-dir", applicationsDir], { cwd: path.resolve(__dirname, ".."), encoding: "utf8" })) as { registered: number; skipped: Array<{ reason: string }> }; }
beforeEach(() => { tempDir = mkdtempSync(path.join(tmpdir(), "jobtracker-backfill-")); dbPath = path.join(tempDir, "test.sqlite"); applicationsDir = path.join(tempDir, "applications"); const db = new Database(dbPath); db.exec("CREATE TABLE opportunities (id TEXT PRIMARY KEY, type TEXT NOT NULL, label TEXT NOT NULL, organization TEXT, status TEXT NOT NULL, priority TEXT NOT NULL, summary TEXT, origin_opportunity_id TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL); CREATE TABLE job_opportunity_details (opportunity_id TEXT PRIMARY KEY, url TEXT, source TEXT, location TEXT, contact TEXT, applied_date TEXT);"); db.prepare("INSERT INTO opportunities VALUES ('job-id', 'job', 'Frontend Engineer', 'Acme', 'wishlist', 'medium', NULL, NULL, ?, ?)").run("2026-01-01T00:00:00.000Z", "2026-01-01T00:00:00.000Z"); db.prepare("INSERT INTO job_opportunity_details VALUES ('job-id', NULL, NULL, NULL, NULL, NULL)").run(); db.close(); });
afterEach(() => { rmSync(tempDir, { force: true, recursive: true }); });
describe("backfill-application-artifacts CLI", () => { it("backfills matching files into opportunity artifacts idempotently", () => { const dir = path.join(applicationsDir, "Acme"); mkdirSync(dir, { recursive: true }); writeFileSync(path.join(dir, "frontend-engineer-fit-analysis.md"), "# Fit"); writeFileSync(path.join(dir, "Example Candidate Resume.pdf"), "pdf"); expect(run()).toMatchObject({ registered: 2, skipped: [] }); expect(run()).toMatchObject({ registered: 2 }); const db = new Database(dbPath); try { expect(db.prepare("SELECT COUNT(*) AS count FROM opportunity_artifacts WHERE opportunity_id = 'job-id'").get()).toEqual({ count: 2 }); } finally { db.close(); } }); });
