import { spawnSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import Database from "better-sqlite3";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { ensureOpportunitySchema } from "./lib/opportunity-schema.mjs";
import { initializeDatabaseIdentity } from "./lib/jobtracker-database-identity.mjs";
import { acquireDailyJobPrepLock } from "./lib/daily-job-prep-lock.mjs";

const root = path.resolve(__dirname, ".."); let dir: string; let dbPath: string; let identity: string; let token: string;
function assessment(state = "open", score = "direct") { return { schemaVersion: 1, posting: { url: "https://example.com/jobs/engineering-manager#top", organization: "Example Co", role: "Engineering Manager", source: "Example", state, location: "Remote", evaluatedAt: "2026-07-22T00:00:00.000Z" }, groups: [["required_qualifications",50],["seniority_leadership",20],["technical_domain",15],["product_delivery_customer",10],["logistics_employment",5]].map(([name, weight]) => ({ name, criteria: [{ id: String(name), requirement: "x", mandatory: name === "required_qualifications", evidence: score, evidenceText: score === "unsupported" ? "" : "x", rationale: "x", weight }] })), blockers: [] }; }
function input(overrides: Record<string, unknown> = {}) { return { assessment: assessment(), posting: { company: " Example Co ", role: "Engineering Manager", url: "https://example.com/jobs/engineering-manager", source: "Example", location: "Remote", posting_state: "open", ...overrides } }; }
function run(payload: unknown, extras: string[] = []) { return spawnSync(process.execPath, ["scripts/prepare-qualified-job.mjs", "--db", dbPath, "--expected-database-id", identity, "--lock-token", token, "--input-json", "-", ...extras], { cwd: root, encoding: "utf8", input: JSON.stringify(payload) }); }
function upsert(args: string[]) { return JSON.parse(spawnSync(process.execPath, ["scripts/upsert-job-posting.mjs", "--db", dbPath, ...args], { cwd: root, encoding: "utf8" }).stdout); }
beforeEach(() => { dir = mkdtempSync(path.join(tmpdir(), "qualified-intake-")); dbPath = path.join(dir, "tracker.sqlite"); const db = new Database(dbPath); ensureOpportunitySchema(db); db.close(); identity = initializeDatabaseIdentity(dbPath).instanceId; token = acquireDailyJobPrepLock(dbPath).token; }); afterEach(() => rmSync(dir, { recursive: true, force: true }));
describe("prepare-qualified-job", () => {
  it("returns skip_ineligible before dry-run and leaves tracker state unchanged", () => { const value = input(); (value.assessment.groups[0].criteria[0] as any).evidence = "unsupported"; const before = readFileSync(dbPath); const result = run(value); expect(result.status).toBe(0); expect(JSON.parse(result.stdout)).toMatchObject({ decision: "skip_ineligible", opportunity: null, dossier: null, preparationPrecondition: null }); expect(readFileSync(dbPath)).toEqual(before); });
  it.each(["rejected", "archived"])("returns skip_inactive without touching a %s record", status => { upsert(["--company", "Example Co", "--role", "Engineering Manager", "--url", "https://example.com/jobs/engineering-manager", "--status", status, "--posting-state", "closed"]); const before = readFileSync(dbPath); const result = run(input()); expect(result.status).toBe(0); expect(JSON.parse(result.stdout).decision).toBe("skip_inactive"); expect(readFileSync(dbPath)).toEqual(before); });
  it("returns prepare_dossier and creates one wishlist row for a new eligible posting", () => { const result = run(input()); expect(result.status).toBe(0); const value = JSON.parse(result.stdout); expect(value).toMatchObject({ schemaVersion: 1, decision: "prepare_dossier", opportunity: { organization: "Example Co", label: "Engineering Manager", status: "wishlist" }, preparationPrecondition: { status: "wishlist", updatedAt: expect.any(String) } }); });
  it("rejects mismatched identity, locks, posting facts, closed intake, and submit options before mutation", () => { const before = readFileSync(dbPath); expect(spawnSync(process.execPath, ["scripts/prepare-qualified-job.mjs", "--db", dbPath, "--expected-database-id", "00000000-0000-4000-8000-000000000000", "--lock-token", token, "--input-json", "-"], { cwd: root, encoding: "utf8", input: JSON.stringify(input()) }).status).toBe(1); expect(run(input({ company: "Wrong" })).status).toBe(1); const closed = input(); closed.posting.posting_state = "closed"; expect(run(closed).status).toBe(1); expect(run({ ...input(), submit: true }).status).toBe(1); expect(run(input(), ["--submit"]).status).toBe(1); expect(readFileSync(dbPath)).toEqual(before); });
  it("returns skip_complete or repair_dossier for unchanged existing records", () => { const created = upsert(["--company", "Example Co", "--role", "Engineering Manager", "--url", "https://example.com/jobs/engineering-manager", "--source", "Example", "--location", "Remote", "--posting-state", "open"]); const db = new Database(dbPath); for (const [type, title] of [["resume","Resume"],["fit_analysis","Fit"],["cover_letter","Cover"],["outreach_message","Outreach"],["other","Submission Guide"]]) { const file = path.join(dir, `${type}.md`); writeFileSync(file, title); db.prepare("INSERT INTO opportunity_artifacts VALUES (?, ?, ?, ?, ?, 'text/markdown', ?, ?)").run(`${type}-id`, created.opportunity.id, type, title, file, "2026-01-01T00:00:00.000Z", "2026-01-01T00:00:00.000Z"); } db.close(); expect(JSON.parse(run(input()).stdout).decision).toBe("skip_complete"); const d = new Database(dbPath); d.prepare("DELETE FROM opportunity_artifacts WHERE type='cover_letter'").run(); d.close(); expect(JSON.parse(run(input()).stdout)).toMatchObject({ decision: "repair_dossier", preparationPrecondition: { opportunityId: created.opportunity.id, status: "wishlist" } }); });
});
