#!/usr/bin/env node
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { createInterface } from "node:readline/promises";
import { stdin as input, stdout as output } from "node:process";
import { fileURLToPath, pathToFileURL } from "node:url";

import { installAllSkills } from "./lib/install-skills.mjs";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const nonInteractive = process.argv.includes("--yes");
const MINIMUM_NODE_VERSION = [20, 18, 1];

export function assertSupportedNodeVersion(version = process.versions.node) {
  const match = /^(\d+)\.(\d+)\.(\d+)/.exec(version);
  const actual = match ? match.slice(1).map(Number) : [];
  let comparison = 0;
  if (actual.length === 3) {
    for (let index = 0; index < MINIMUM_NODE_VERSION.length; index += 1) {
      if (actual[index] === MINIMUM_NODE_VERSION[index]) continue;
      comparison = actual[index] > MINIMUM_NODE_VERSION[index] ? 1 : -1;
      break;
    }
  }
  if (actual.length !== 3 || comparison < 0) {
    throw new Error("JobTracker setup requires Node.js 20.18.1 or newer.");
  }
}

function expandHome(value) {
  if (!value.startsWith("~")) {
    return value;
  }

  if (!process.env.HOME) {
    return value;
  }

  if (value === "~") {
    return process.env.HOME;
  }

  if (value.startsWith("~/")) {
    return path.join(process.env.HOME, value.slice(2));
  }

  return value;
}

function resolveUserPath(value, fallback) {
  const selected = value.trim() || fallback;
  const expanded = expandHome(selected);
  return path.isAbsolute(expanded) ? expanded : path.resolve(projectRoot, expanded);
}

function quoteEnv(value) {
  return `"${String(value).replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n")}"`;
}

async function ask(question, fallback, rl) {
  if (nonInteractive) {
    return fallback;
  }

  const suffix = fallback ? ` [${fallback}]` : "";
  const answer = await rl.question(`${question}${suffix}: `);
  return answer.trim() || fallback;
}

const defaults = {
  dbPath: path.join(projectRoot, "data", "jobtracker.sqlite"),
  applicationsDir: path.join(projectRoot, "applications"),
  baseResumePath: "",
  linkedInUrl: "",
  aiProvider: "",
  installSkills: "Y"
};

export async function runSetup() {
  assertSupportedNodeVersion();
  const rl = nonInteractive ? null : createInterface({ input, output });
  try {
    const dbPath = resolveUserPath(
      await ask("SQLite database path", defaults.dbPath, rl),
      defaults.dbPath
    );
    const applicationsDir = resolveUserPath(
      await ask("Application materials directory", defaults.applicationsDir, rl),
      defaults.applicationsDir
    );
    const baseResumeInput = await ask("Base resume path (optional)", defaults.baseResumePath, rl);
    const baseResumePath = baseResumeInput ? resolveUserPath(baseResumeInput, "") : "";
    const linkedInUrl = await ask("LinkedIn/profile URL (optional)", defaults.linkedInUrl, rl);
    const aiProvider = await ask(
      "AI service note, credentials configured outside this repo (optional)",
      defaults.aiProvider,
      rl
    );
    const installAnswer = await ask(
      "Install bundled Codex and Claude skills now? Y/n",
      defaults.installSkills,
      rl
    );

    mkdirSync(path.dirname(dbPath), { recursive: true });
    mkdirSync(applicationsDir, { recursive: true });

    const envLocal = [
      "# Generated by npm run setup. Do not commit this file.",
      `JOBTRACKER_DB_PATH=${quoteEnv(dbPath)}`,
      `JOBTRACKER_APPLICATIONS_DIR=${quoteEnv(applicationsDir)}`,
      `JOBTRACKER_BASE_RESUME_PATH=${quoteEnv(baseResumePath)}`,
      `JOBTRACKER_LINKEDIN_URL=${quoteEnv(linkedInUrl)}`,
      `JOBTRACKER_AI_PROVIDER=${quoteEnv(aiProvider)}`,
      ""
    ].join("\n");

    writeFileSync(path.join(projectRoot, ".env.local"), envLocal, "utf8");

    console.log("Wrote .env.local");
    console.log(`Database path: ${dbPath}`);
    console.log(`Application materials directory: ${applicationsDir}`);

    if (!/^n/i.test(installAnswer)) {
      const result = installAllSkills(projectRoot);
      for (const [provider, installed] of Object.entries(result)) {
        console.log(`Installed ${installed.skillNames.length} ${provider} skills to ${installed.targetRoot}:`);
        for (const skillName of installed.skillNames) {
          console.log(`- ${skillName}`);
        }
      }
    }
  } finally {
    rl?.close();
  }
}

const isMain = process.argv[1] && pathToFileURL(path.resolve(process.argv[1])).href === import.meta.url;
if (isMain) {
  runSetup().catch((error) => {
    console.error(error instanceof Error ? error.message : "JobTracker setup failed.");
    process.exitCode = 1;
  });
}
